### PR TITLE
Additional features to rundeck driver

### PR DESCRIPTION
**Pull request by anojansivarajah**

### CODE REVIEW

**Comment by trentdavida** [comment]
I love the idea of being able to get additional output in Slack of the job run, but I think it should be parameterized in the Actions File. Same goes for the Running jobs as Slack Users. Our Slack Names aren't governed by Active Directory, but Rundeck is. Adding this feature as Requirement would make this Useless to us as we would have to manually map Slack users to Rundeck users.

**Comment by anojansivarajah** [comment]
not running as the slack user won't give any benefits as all jobs will be run by the same user who owns the api token. Current version of Rundeck does not require the user to exist to run a job as that user

I will try to parameterize the log output and may be a template of what outputs the bot should give back when i get some time

**Comment by trentdavida** [comment]
I understand now what you mean by the Slack user, That's really slick. I've also been looking into adding the parameterization for the log output. I'll run it by you when I have something actionable.

**Comment by anojansivarajah** [comment]
I got something done with 2 parameters under options

**Comment by outofcoffee** [comment]
Hi folks, this is great work, thank you.

I would appreciate it if you could rebsee on develop, which is where new features should land first.

What would you think about splitting some of these features into separate PRs, to make review a bit easier?

**Comment by anojansivarajah** [comment]
Hi @outofcoffee 
I will create 3 pull requests to dev
1) Running job as slack user
2) enable/disable job info
3) enable/disable get job output

**Comment by anojansivarajah** [comment]
@outofcoffee Please look at pull requests #4  and #8

**Comment by outofcoffee** [comment]
> FYI: Currently in develop each request is handled twice

Ah, really? Do you know what might be causing this?

**Comment by anojansivarajah** [comment]
This pull request is no longer needed

**Comment by outofcoffee** [comment]
@anojansivarajah please could you elaborate on your comment about requests being handled twice?

**Pull request closed without merging**
